### ISSUE TITLE
How to make two inputs of range date-piacker.

### ISSUE THREAD

**Issue by keem1201** [yscoder/Calendar#1]
Here I would like to have two inputs of range date-piacker. For example; when I already selected a check-in date, it will automatically force me to select a check-out date.

Thanks
Hakeem

**Comment by yscoder** [comment]
Do you want to select a date range?
I think you need to use two date picker to complete.

**Comment by keem1201** [comment]
Yes. Can you help me coding it? Thanks

**Comment by yscoder** [comment]
I guess, you want to see in the view select the date range.
The following code only shows the results of two separate selection. Maybe not what you want.

```
<input type="text" id="startDate">
<div id="dt1"></div>

<input type="text" id="endDate">
<div id="dt2"></div>
```

```
$('#startDate').calendar({
    trigger: '#dt1',
    zIndex: 999
});

$('#endDate').calendar({
    trigger: '#dt2',
    zIndex: 999
});
```

**Comment by keem1201** [comment]
Thanks
