### ISSUE TITLE
一个页面能不能多个控件使用一个控件

### ISSUE THREAD

**Issue by jasonx4131** [yscoder/Calendar#7]
一个页面有多个input，只日历控件只需要一个。这个怎么弄？
另外我想问下，动态添加的input，怎么绑定日历事件

**Comment by yscoder** [comment]
等我的提交。

**Comment by yscoder** [comment]
一开始没有考虑过多个 input 对应一个日历的场景，现在改起来比较麻烦。
提交了对动态创建 input 元素的支持，demo 里有相关代码。
